### ISSUE TITLE
Exploration mode -> Validation mode

### ISSUE THREAD

**Issue by Metais** [asreview/asreview-academy#24]
Hi there,

I was doing a tutorial of ASReview and came across the use of 'Exploration' mode, which I think is now renamed to 'Validation' mode. I wanted to edit the use of this term throughout the asreview-academy repository and push it on a separate branch, for you guys to review/merge it, but unfortunately (and understandably!) people don't have access to just randomly create branches and commit changes.

I [forked the project instead](https://github.com/Metais/asreview-academy), it contains the updated branch (as well as a screenshot that should replace one of the images). Maybe this is useful for you guys? I hope it helps to keep the docs up-to-date! :)

**Comment by VeenDuco** [comment]
Hello @Metais, That is wonderful. Could you make a pull request so that we can merge it? That would be a great contribution! If you don't know how to do that, let me know and I'll help you out.
